name: CI/CD

on: [push]

jobs:
  cicd:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: [3.6]
        poetry-version: [1.1.4]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Before publish
        run: |
          poetry install
          poetry build
          poetry config repositories.test https://test.pypi.org/legacy/
      - name: Test
        run: |
          poetry --version
          poetry version
          poetry run behave
      - uses: dorny/paths-filter@v2
        id: Publish
        with:
          filters: |
            toml:
              - 'pyproject.toml'

        # run only if pyproject.toml was changed
        if: steps.changes.outputs.src == 'true'
        #run: poetry publish -r test -u "${{ secrets.PYPI_USERNAME }}" -p "${{ secrets.PYPI_PASSWORD }}"
        run: poetry publish -u "${{ secrets.PYPI_USERNAME }}" -p "${{ secrets.PYPI_PASSWORD }}"
