on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PLATFORM: linux/amd64,linux/arm64

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: build and push images
        run: |
          docker build --push --platform $PLATFORM -t openremote/openremote-cli:latest .
